[package]
name = "miauw"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters-iced = "0.11"
iced = {version="0.13", features=["advanced", "debug", "canvas"]}
iced_graphics = "0.13"
iced_core = "0.13"
plotters = "0.3"
num-complex = "0.4"